name: web_scss
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.4.3

# Add regular dependencies here.
dependencies:
  sass: ^1.77.6
  shelf: ^1.4.2
  shelf_hotreload: ^1.5.0
  shelf_router: ^1.1.4
  shelf_static: ^1.1.2
  # path: ^1.8.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
